# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

FROM openjdk:8-jdk-alpine
#COPY manifest.mf manfest.mf
COPY target/dac-exemplo-2-1.0-SNAPSHOT-jar-with-dependencies.jar dac-exemplo-2-1.0-SNAPSHOT-jar-with-dependencies.jar
CMD ["java","-jar", "dac-exemplo-2-1.0-SNAPSHOT-jar-with-dependencies.jar"]
# ENTRYPOINT java -jar dac-exemplo-2.jar
